version: '3.7'

services:
  orchestrator:
    environment:
      - PORT=9090
      - NETMASK=10.0.5.0/24
    build:
      context: ./services/orchestrator
      dockerfile: Dockerfile
    
    ports:
      - '9090:9090'
